apiVersion: v1
kind: Secret
metadata:
  name: medbook-secrets
  namespace: medbook
type: Opaque
stringData:
  mongo-uri: "mongodb://mongo:27017/medbook"
  jwt-secret: "UJeIvA9VePBtLSQX"
  session-secret: "super_secret_123456789"
